### PR TITLE
Compiler Directives docs improvements/fixes

### PR DESCRIPTION
**Pull request by Ragnar-F**
These changes improve the Compiler Directives docs to be more consistent with the other docs, and fix format issues. For details and reasons, see the commit messages. Basically, these changes only affect the formats of the docs - the content is almost unchanged.

### CODE REVIEW

**Comment by TAC109** [comment]
@Ragnar-F 
Scripts.htm - Ahk2Exe -  I'd like it to be more obvious that the first two parameter pairs are "use either, but one is mandatory" while the others are optional. If you don't like my method of showing this, can we do more solid lines in the table around the '/in' and '/inGui' parameters, and adjust the wording somehow. I just feel that your layout could lead to user confusion. What are your thoughts on this?

The 'Exclude compiler directives/vars from syntax highlighter' commit. While I can understand the reason for this, I originally felt that this change of mine provided a convenient method of selecting Compiler directives in the index list. After all it would be easy for the user to distinguish between Compiler directives and the Ahk directives, as the Ahk directives all start with '#' and appear first in the list.

Also, in the same commit, to be consistent with other entries which use parentheses should 'compiler' be 'Compiler' in all entries?

**Comment by Ragnar-F** [comment]
> Scripts.htm - Ahk2Exe - I'd like it to be more obvious that the first two parameter pairs are "use either, but one is mandatory" while the others are optional. If you don't like my method of showing this, can we do more solid lines in the table around the '/in' and '/inGui' parameters, and adjust the wording somehow. I just feel that your layout could lead to user confusion. What are your thoughts on this?

You're right. I have recombined the two parameters, almost identical to the previous state. Take a look and see if you like it better this way.

> The 'Exclude compiler directives/vars from syntax highlighter' commit. While I can understand the reason for this, I originally felt that this change of mine provided a convenient method of selecting Compiler directives in the index list. After all it would be easy for the user to distinguish between Compiler directives and the Ahk directives, as the Ahk directives all start with '#' and appear first in the list.

I was aware of your intentions, but this is not the right way. The additional numbers at each index entry not only affect the filter, but also the syntax highlighter, which currently assumes that these are only AHK directives and treats them accordingly. This means that there may be inconsistencies in highlighting.

It should not be too difficult to simply create a separate filter without affecting the highlighter.

> Also, in the same commit, to be consistent with other entries which use parentheses should 'compiler' be 'Compiler' in all entries?

There is no clear consistency. But what actually predominates is the fact that proper nouns are capitalized, and the rest is lower case. Compiler is not a proper noun.

**Comment by TAC109** [comment]
Well, this is looking great!

A couple of further changes might be needed:

- in Ahk2ExeDirectives under 'Bin' description there’s a reference to #Include. Could you href this please?

- The Ahk2Exe Compiler index filter looks really good! Thanks for doing this. But the  'BinMod directive' entry is not strictly accurate. (It is actually a reference to a supplied script the user can run via the PostExec directive.) Could you change this to 'BinMod script (Ahk2Exe)' please?

Thanks again for your help with this.

**Comment by Ragnar-F** [comment]
Done.

**Pull request merged**
